---
- hosts: local
  sudo: yes
  
  tasks: 
    - action: ec2_remote_facts
      filters:
        instance-state-name: running
        "tag:Name": ProdServer
    - name Conditionally provision a new instance. 
        
    
